# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
<<<<<<< HEAD
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
=======
    branches: [ "branch" ]
  pull_request:
    branches: [ "branch" ]
>>>>>>> 9d2e324 (Create python-app.yml)

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
<<<<<<< HEAD
        pip install bandit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with bandit
      run: |
        bandit -r . -x test_*.py
    - name: Test with pytest
      run: |
        pytest
=======
        pip install bandit pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with bandit
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        bandit -r . -x test_*.py
>>>>>>> 9d2e324 (Create python-app.yml)
